### ISSUE TITLE
Name field size is too long

### ISSUE THREAD

**Issue by bfuerea** [bfuerea/ImaDev#3]
![image](https://user-images.githubusercontent.com/18399890/134714630-c41c23c2-ea09-4569-b5ec-9ca7331023c6.png)

**Comment by PuneetDabral** [comment]
can i do my first contribution here if you help me i can boost my confidance

**Comment by bfuerea** [comment]
> can i do my first contribution here if you help me i can boost my Confidence

hey! Feel free to fork and send a pull request with fix

**Comment by PuneetDabral** [comment]
can you please help me to resolve this...

**Comment by bfuerea** [comment]
fixed in https://github.com/bfuerea/ImaDev/commit/2f997e26d340410f4387c7415e41a245a2a03dac
